name: flutter_login_screen
description: Functional Flutter Starter Kit
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: 2.3.2
  firebase_core: 3.6.0
  firebase_auth: 5.3.1
  cloud_firestore: 5.4.4
  flutter_easyloading: 3.0.5
  flutter_facebook_auth: 7.0.1
  http: 1.2.2
  image_picker: 1.1.2
  firebase_storage: 12.3.2
  cached_network_image: 3.4.1
  smooth_page_indicator: 1.2.0+3
  the_apple_sign_in: 1.1.1
  bloc: 8.1.4
  flutter_bloc: 8.1.6
  url_launcher: 6.3.0
  cupertino_icons: 1.0.8

dev_dependencies:
  flutter_lints: 5.0.0
  flutter_launcher_icons: 0.14.1

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/ic_launcher-playstore.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/